[features]
seeds = false
skip-lint = false
[programs.devnet]
vrf_client = "HdouAH5FeuxSUoeGJvLHibgW4cnfsuhqrrLwFhiZzQoa"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/johnliu/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 20000

[test.validator]
url = "https://devnet.genesysgo.net/"

[[test.validator.clone]] # programID
address = "2TfB33aLaneQb5TNVwyDz3jSZXS6jdW2ARw1Dgf84XCG"

[[test.validator.clone]] # idlAddress
address = "CKwZcshn4XDvhaWVH9EXnk3iu19t6t5xP2Sy2pD6TRDp"

[[test.validator.clone]] # programState
address = "BYM81n8HvTJuqZU1PmTVcwZ9G8uoji7FKM6EaPkwphPt"

[[test.validator.clone]] # switchboardVault
address = "FVLfR6C2ckZhbSwBzZY4CX7YBcddUSge5BNeGQv5eKhy"

[[test.validator.clone]] # tokenWallet
address = "GSexndy5bqjLMT4FJPS2es6T5LmXT3rEtWesbN6xxoQS"

[[test.validator.clone]] # queue
address = "AMQTxWKC151RHHadPQm2375PhoNRtVBy1kAmmmPKzDVi"

[[test.validator.clone]] # queueAuthority
address = "DfLZV18rD7wCQwjYvhTFwuvLh49WSbXFeJFPQb5czifH"

[[test.validator.clone]] # queueBuffer
address = "E2PSD9Kg8ycawGhdi5M4ENm2KD18Hy6cYvgkG78eBe5X"

[[test.validator.clone]] # crank
address = "6Ckq6NUMRFHt24rxGxvSu23wCzTs6WwAp45FxQ64gFqJ"

[[test.validator.clone]] # crankBuffer
address = "HrTVfCFHHXnK5B1pLEgvbPUFERfaQg7eHQqN5KpvyC7H"

[[test.validator.clone]] # oracle
address = "3AM3jAcd93uAcG5xekZDXyose68299KihJponr1iEo1w"

[[test.validator.clone]] # oracleAuthority
address = "DfLZV18rD7wCQwjYvhTFwuvLh49WSbXFeJFPQb5czifH"

[[test.validator.clone]] # oracleEscrow
address = "BGH3u5fVe9T8F1aRs3qGYdAbiKy6vHCSvCMwqcpLUMfU"

[[test.validator.clone]] # oraclePermissions
address = "41WNUhaabCvRvvxwoyLBiZwdD2mSovmKui8JjhatDxjz"
